version: "3.9"  # optional since v1.27.0

services:
  mariadb:
    build:
      context: requirements/mariadb/.
      args:
            DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    image: mariadb:mariadb
    container_name: "mariadb"
    restart: always
    networks:
      - inception
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - 'mariadb:/var/lib/mysql/'
  wordpress:
    build: requirements/wordpress/.
    image: wordpress:wordpress
    container_name: "wordpress"
    restart: always
    networks:
      - inception
    ports:
      - "9000:9000"
    volumes:
      - 'wordpress:/var/www/'
  nginx:
    build: requirements/nginx/.
    image: nginx:nginx
    container_name: "nginx"
    restart: always
    networks:
      - inception
    ports:
      - "443:443"
    volumes:
      - 'wordpress:/var/www/'

networks:   
  inception:
    driver: bridge

volumes:
 wordpress:
  driver: local
  driver_opts:
   o: bind
   type: ext4
   device: /home/melghoud/data/wordpress
 mariadb:
  driver: local
  driver_opts:
   o: bind
   type: ext4
   device: /home/melghoud/data/mariadb